### ISSUE TITLE
Can't get bot's name

### ISSUE THREAD

**Issue by Xwudao** [medama-io/go-useragent#27]
would be like `mileusna/useragent`: 
```go
import (
	"time"

	"github.com/gin-gonic/gin"
	"github.com/mileusna/useragent"
)

func RobotMdw() gin.HandlerFunc {
	return func(c *gin.Context) {
		var now = time.Now()
		parse := useragent.Parse(c.Request.UserAgent())
		if parse.Bot {
			_ = rdc.SetBotVisit(c.Request.Context(), now.Format(time.DateOnly), parse.Name)
		}
	}
}

```

**Comment by ayuhito** [comment]
This is possible to implement, but thinking about this more I'm unsure if it's worth supporting because there are an endless number of bots. It's an endless task that will constantly change compared to a relatively small number of browsers.

For example - for browsers, we have to _manually_ map each browser token to a name:
https://github.com/medama-io/go-useragent/blob/main/internal/match.go#L62

If we have to individually name bots, we have to remove the simplification of this map that generically treats all these tokens as "Bot" and instead manually map each token to a unique const. That's a lot of work to maintain and reduces our bot coverage significantly since we can use simpler tokens like "bot" to match on a variety of bot useragents like "facebookbot" or "googlebot" etc.
