### ISSUE TITLE
How can I tell if it's a different device by ua?

### ISSUE THREAD

**Issue by huhu415** [medama-io/go-useragent#46]
Can I tell the difference with this splicing?    Or do I need to do something else?

```go
func (u *ParserRecord) Parser(uaString string) {
	ua := u.uaParser.Parse(uaString)
	key := boolToString(ua.IsDesktop()) + boolToString(ua.IsMobile()) + boolToString(ua.IsTablet()) + ua.GetOS()
	u.record[key].Add(1)
}
```

**Comment by huhu415** [comment]
If you use raw strings, the ua field should be different for different browsers on the same device, so can't use raw strings yet.

**Comment by ayuhito** [comment]
If that is the case, generating a custom key could be okay but I feel it would be likely lacking in accuracy unless that's not an issue for you. Also, I would recommend generating the key with `fmt.Sprintf` instead of casting + concatenation if you do go ahead with that approach. 

More likely, you may want to rely on a more normal regex-based parser like [`uap-go`](https://github.com/ua-parser/uap-go) which also has a `Device` property that you could use more practically. Adding that level of granularity is unfortunately out of scope for this project.

**Comment by huhu415** [comment]
Ok thanks, I'll check it out, but what do you mean by custom key? Does the server return a token, and then define the device?

**Comment by ayuhito** [comment]
> what do you mean by custom key

Ah, I was referring to the `key` variable in your original post.
